# NOTE: Unlike a typical YAML file, ordering is significant in this file.

# Uncomment the following line to set the default configuration to load on power on.
# The default is selected by `id` (not `name`) and must match one of the configurations
# defined below.
#
# The boot menu will still be accessible by long-pressing the "Menu" button after boot.
#
# default: pet-40xx-60hz

configs:
  - id: pet-40xx-50hz
    name: "CBM 40xx (40 Col 50 Hz)"
    setup:
      - action: "load"
        files:
          - address: 0xb000
            file: "/roms/basic-4-b000.901465-23.bin"
          - address: 0xc000
            file: "/roms/basic-4-c000.901465-20.bin"
          - address: 0xd000
            file: "/roms/basic-4-d000.901465-21.bin"
          - address: 0xe000
            file: "/roms/edit-4-40-n-50Hz.901498-01.bin"
          - address: 0xf000
            file: "/roms/kernal-4.901465-22.bin"
          - address: 0x68000
            file: "/roms/characters-2.901447-10.bin"
      - action: "set"
        usb-keymap: "/ukm/us.bin"
        video-ram-kb: 1
        tape: "2ef415f4c9cad1d4da"
      - if: "graphics"
        else:
          # Commodore never produced an edit ROM for the business keyboard for 40 column models.
          # This patch replaces the original keyscan routine with one adapted from the 80 column
          # edit rom '901474-03'.
          - action: "patch"
            address: 0xe55c
            hex: "aa08297f28301746989013c92c900dc93cb009e90fc920b00569202c"
          # Business keyboard scanmap from '901474-03'
          - action: "patch"
            address: 0xe73f
            hex: "16043a03393633dfb12f15134d205812b2100fb02c4e565ab30019ae2e424300b4db4f1155544551145049dc59525709b6c04c0d4a474441b53b4bdd4846539bb906deb7b0373431050e1db82d383532"
  - id: pet-40xx-60hz
    name: "PET 40xx (40 Col 60 Hz)"
    setup:
      - action: "load"
        files:
          - address: 0xb000
            file: "/roms/basic-4-b000.901465-23.bin"
          - address: 0xc000
            file: "/roms/basic-4-c000.901465-20.bin"
          - address: 0xd000
            file: "/roms/basic-4-d000.901465-21.bin"
          - address: 0xe000
            file: "/roms/edit-4-40-n-60Hz.901499-01.bin"
          - address: 0xf000
            file: "/roms/kernal-4.901465-22.bin"
          - address: 0x68000
            file: "/roms/characters-2.901447-10.bin"
      - action: "set"
        usb-keymap: "/ukm/us.bin"
        video-ram-kb: 1
        tape: "2ef415f4c9cad1d4da"
      - if: "graphics"
        else:
          # Commodore never produced an edit ROM for the business keyboard for 40 column models.
          # This patch replaces the original keyscan routine with one adapted from the 80 column
          # edit rom '901474-03'.
          - action: "patch"
            address: 0xe55c
            hex: "aa08297f28301746989013c92c900dc93cb009e90fc920b00569202c"
          # Business keyboard scanmap from '901474-03'
          - action: "patch"
            address: 0xe73f
            hex: "16043a03393633dfb12f15134d205812b2100fb02c4e565ab30019ae2e424300b4db4f1155544551145049dc59525709b6c04c0d4a474441b53b4bdd4846539bb906deb7b0373431050e1db82d383532"
  - id: pet-80xx-50hz
    name: "CBM 80xx (80 Col 50 Hz)"
    setup:
      - action: "load"
        files:
          - file: "/roms/basic-4-b000.901465-23.bin"
            address: 0xb000
          - file: "/roms/basic-4-c000.901465-20.bin"
            address: 0xc000
          - file: "/roms/basic-4-d000.901465-21.bin"
            address: 0xd000
          - file: "/roms/edit-4-80-b-50Hz.901474-04-3681.bin"
            address: 0xe000
          - file: "/roms/kernal-4.901465-22.bin"
            address: 0xf000
          - file: "/roms/characters-2.901447-10.bin"
            address: 0x68000
      - if: "graphics"
        then:
          # Commodore never produced an edit ROM for the graphics keyboard for 80 column models.
          # This patch replaces the original keyscan routine with one adapted from the 40 column
          # edit rom '901499-01'.
          - action: "patch"
            address: 0x0e545
            hex: "eaeaeaeaeaeaea46989013eaeaeaeaeaeaeaeaeaeaeaeaeaeaeaeaea"
          # Graphics keyboard scanmap from '901499-01'
          - action: "patch"
            address: 0x0e6d1
            hex: "3d2e10033c205b122d30003eff5d40002b32ff3f2c4e565833310d3b4d42435a2a35ff3a4b4846533634ff4c4a4744412f38ff504959525739375e4f55544551141109295c2724221d135f2826252321"
          # Because we patched the editor ROM, we should fix the checksum.
          - action: "fix-checksum"
            checksum: 0xe0
            start-addr: 0xe000
            end-addr: 0xe7ff
            fix-addr: 0xe7ff
      - action: "set"
        usb-keymap: "/ukm/us.bin"
        columns: 80
        video-ram-kb: 2
        tape: "2ef415f4c9cad1d4da"
  - id: pet-80xx-60hz
    name: "PET 80xx (80 Col 60 Hz)"
    setup:
      - action: "load"
        files:
          - file: "/roms/basic-4-b000.901465-23.bin"
            address: 0xb000
          - file: "/roms/basic-4-c000.901465-20.bin"
            address: 0xc000
          - file: "/roms/basic-4-d000.901465-21.bin"
            address: 0xd000
          - file: "/roms/edit-4-80-b-60Hz.901474-03.bin"
            address: 0xe000
          - file: "/roms/kernal-4.901465-22.bin"
            address: 0xf000
          - file: "/roms/characters-2.901447-10.bin"
            address: 0x68000
      - if: "graphics"
        then:
          # Commodore never produced an edit ROM for the graphics keyboard for 80 column models.
          # This patch replaces the original keyscan routine with one adapted from the 40 column
          # edit rom '901499-01'.
          - action: "patch"
            address: 0x0e545
            hex: "eaeaeaeaeaeaea46989013eaeaeaeaeaeaeaeaeaeaeaeaeaeaeaeaea"
          # Graphics keyboard scanmap from '901499-01'
          - action: "patch"
            address: 0x0e6d1
            hex: "3d2e10033c205b122d30003eff5d40002b32ff3f2c4e565833310d3b4d42435a2a35ff3a4b4846533634ff4c4a4744412f38ff504959525739375e4f55544551141109295c2724221d135f2826252321"
      - action: "set"
        usb-keymap: "/ukm/us.bin"
        columns: 80
        video-ram-kb: 2
        tape: "2ef415f4c9cad1d4da"
  - id: pet-2001
    name: "PET 2001 (Upgraded ROMs)"
    setup:
      - action: "load"
        files:
          - address: 0xc000
            file: "/roms/basic-2-c000.901465-01.bin"
          - address: 0xd000
            file: "/roms/basic-2-d000.901465-02.bin"
          - address: 0xf000
            file: "/roms/kernal-2.901465-03.bin"
          - address: 0x68000
            file: "/roms/characters-2.901447-10.bin"
      - if: "graphics"
        then:
          # Load editor ROM for graphics keyboard.
          - action: "load"
            files:
            - address: 0xe000
              file: "/roms/edit-2-n.901447-24.bin"
          # Upgrade ROMs for the graphics keyboard continued to delay screen updates until
          # the beam was outside the visible region to avoid "sparkle" artifacts.
          #
          # On later CRTC models, the polling is unnecessary and results in extremely slow
          # text output due to VIA/PB5 being connected to VERT instead of VIDEO_ON/SYNC.
          #
          # The patch below elides the polling loop.
          - action: "copy"
            source: 0xe6f2
            destination: 0xe6eb
            length: 0x06
        else:
          # For the business keyboard, we use the editor ROM for the 30xxB, which is almost
          # identical except that:
          #
          #   - Starts up in lower case ($e220)
          #   - Polling VIA/PB5 (VIDEO_ON/SYNC) has been removed.
          #   - Minor rearrangements in the $e699-e768 range to make room for the business
          #     keyboard keyscan routine.  Noteably:
          #     - LDTB2 has moved from $e748 to $e74b
          #     - LOAD/RUN string moved from $e760 to $e763 and reduced from 9 to 6 chars
          #       ('lO' instead 'load', etc.)
          - action: "load"
            files:
            - address: 0xe000
              file: "/roms/edit-2-b.901474-01.bin"
          # The 30xxB editor ROM initializes to lower case.  Patch it to upper case.
          - action: "patch"
            address: 0x0e221
            hex: "0c"
      - action: "set"
        usb-keymap: "/ukm/us.bin"
        video-ram-kb: 1
        tape: "eff3d6f3c9cad1d4da"
  - id: pet-2001-rom1
    name: "PET 2001 (Original ROMs)"
    setup:
      - action: "load"
        files:
          - address: 0xc000
            file: "/roms/rom-1-c000.901439-01.bin"
          - address: 0xd000
            file: "/roms/rom-1-d000.901439-02.bin"
          - address: 0xe000
            file: "/roms/rom-1-e000.901439-03.bin"
          - address: 0xf000
            # Instead of "/roms/901439-04.bin", we use a patched ROM for disk drive support:
            # https://hub.inktada.com/channel/rom1diskmagic
            file: "/roms/rom1diskrom_v15.bin"
          - address: 0xc800
            file: "/roms/rom-1-c800.901439-05.bin"
          - address: 0xd800
            file: "/roms/rom-1-d800.901439-06.bin"
          - address: 0xf800
            file: "/roms/rom-1-f800.901439-07.bin"
          - address: 0x68000
            file: "/roms/characters-1.901447-08.bin"
      - if: "graphics"
        else:
          # Commodore never produced an edit ROM for the business keyboard for the original ROM set.
          # This patch replaces the original keyscan routine with one adapted from '901474-01'.
          - action: "patch"
            address: 0x0e7ec
            hex: "e00ad00af0060a6905a00060a2008e0d02d0f800"
          # Business keyboard scanmap from '901474-01'
          - action: "patch"
            address: 0x0e702
            hex: "b01148bd5be7d007a9018d0402d0038e230268caf00888d0e6ee10e8d0d7ad2302cd0302f0318d0302aa302bbd5be708297f2830184e04029013c92c900dc93cb009e90fc920b00569202c0980ae0d029d0f02e820ece74c7ee650e73a03393633dfb12fff134d205812b2ffffb02c4e565ab300ffae2e424300b4db4f1155544551145049dc59525789b6c04c0d4a474441b53b4bdd4846539bb9ffdeb7b0373431ffff1db82d383532"
      # Original ROMs polled VIA ($E840) to delay screen updates until the beam was
      # outside the visible region to avoid "sparkle" artifacts.
      #
      # On later CRTC models, the polling is unnecessary and results in extremely slow
      # text output due to VIA/PB5 being connected to VERT instead of VIDEO_ON/SYNC.
      #
      # The patch below elides the polling loop.
      - action: "copy"
        source: 0xe7b4
        destination: 0xe7ad
        length: 0x06
      - action: "set"
        usb-keymap: "/ukm/us.bin"
        video-ram-kb: 1
        tape: "e5f362f3e5e6eef1f9"
  - id: colourpet-40
    name: "ColourPET (40 Col 60 Hz) [ALPHA]"
    setup:
      - action: "load"
        files:
          - address: 0xb000
            file: "/roms/basic-4-b000.901465-23.bin"
          - address: 0xc000
            file: "/roms/basic-4-c000.901465-20.bin"
          - address: 0xd000
            file: "/roms/basic-4-d000.901465-21.bin"
          - address: 0xf000
            file: "/roms/kernal-4.901465-22.bin"
          - address: 0x68000
            file: "/roms/characters-2.901447-10.bin"
      - if: "graphics"
        then:
          - action: "load"
            files:
              - address: 0xe000
                file: "/roms/colourpet-n40.bin"
        else:
          - action: "load"
            files:
              - address: 0xe000
                file: "/roms/colourpet-b40.bin"
      - action: "set"
        usb-keymap: "/ukm/us.bin"
        columns: 40
        video-ram-kb: 3
        tape: "2ef415f4c9cad1d4da"

  - id: superpet
    name: "SuperPET 6809 (Waterloo)"
    setup:
      # Waterloo ROMs are not included; download from
      # https://www.zimmers.net/anonftp/pub/cbm/firmware/computers/pet/SuperPET/
      # and place in /roms/.
      - action: "load"
        files:
          - address: 0xa000
            file: "/roms/waterloo-a000-bfff.970018-12.bin"
          - address: 0xc000
            file: "/roms/waterloo-c000-dfff.970019-12.bin"
          - address: 0xe000
            file: "/roms/waterloo-e000-ffff-970034-12.bin"
          - address: 0x68000
            file: "/roms/characters.901640-01.bin"
      - action: "set"
        cpu: "6809"
        usb-keymap: "/ukm/us.bin"
        columns: 80
        video-ram-kb: 2
        ieee-drive: "on"
